# This playbook will deploy an Nginx web server on a remote host (AWS EC2 instance)

---
- hosts: all
  become: true
  tasks:
    - name: Install Nginx web server on AWS linux
      yum:
        name: nginx
        state: present

    - name: Start Nginx web server
      service:
        name: nginx
        state: started

    - name: Enable Nginx web server to start at boot time
      service:
        name: nginx
        enabled: true

    - name: Create a new default php file that will display the hostname and ip address of the server as well as the date and time
      template:
        src: index.php.j2
        dest: /usr/share/nginx/html/index.php

    - name: Restart Nginx web server
      service:
        name: nginx
        state: restarted