# -*- mode: ruby -*-
# vi: set ft=ruby :

# this is just a simple test vagrantfile to test the playbook before running it on the real server
# it will create a centos7 vm with 1GB of ram and ip

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "centos7"
  config.vm.network "private_network", ip: "192.168.173.14"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end
end