# This playbook will deploy an Nginx web server on a remote host (AWS EC2 instance)

---
- name: Configure Nginx on Ubuntu Servers
  hosts: all
  become: true

  vars_files:
    - vars.yml

  tasks:
    - name: Update package lists
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Create HTML File with Hostname/IP
      template:
        src: templates/index.html.j2
        dest: /var/www/html/index.html

    - name: Restart Nginx
      systemd:
        name: nginx
        state: restarted